use_frameworks!

target 'NativePod_Example' do
  pod 'NativePod', :path => '../'

  target 'NativePod_Tests' do
    inherit! :search_paths

    pod 'Specta'
  pod 'Expecta'
  pod 'FBSnapshotTestCase'
  pod 'Expecta+Snapshots'
  end
end
